# Generated by Django 3.0.5 on 2020-04-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_artocle_bub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artocle',
            name='likes',
        ),
    ]
