# Generated by Django 3.0.5 on 2020-04-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0003_remove_artocle_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artocle',
            new_name='Article',
        ),
    ]
